# Setup
title:               David2005Yun Notebook
tagline:             'My personal notebook'
description:         'Hello!'
url:                 http://www.20050223.xyz/
baseurl:             'http://david2005yun.github.io/david2005yun/'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/
  email:             1@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
